# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='photography/figures')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-upload_time',),
            },
        ),
    ]
