# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-30 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_auto_20160930_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='f_stop',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='photo',
            name='focal_length',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='photo',
            name='iso',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='photo',
            name='shutter',
            field=models.CharField(max_length=300),
        ),
    ]
