# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_auto_20160930_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='camera',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='f_stop',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='focal_length',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photography/photos'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='iso',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='lens',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='shutter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
