# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_auto_20161004_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-taken_time',)},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='photo',
            name='taken_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
