# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=400)),
                ('abstract', models.TextField()),
                ('pdf', models.FileField(upload_to='publications/')),
                ('pub_date', models.DateField()),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('last_downloaded', models.DateTimeField(blank=True)),
            ],
        ),
    ]
