# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='last_downloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
