# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20160918_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='figure',
            field=models.ImageField(upload_to='research/publications/figures'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf',
            field=models.FileField(upload_to='research/publications/pdfs'),
        ),
    ]
