# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20160918_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_initial', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=400)),
                ('pubmed_link', models.URLField()),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.AddField(
            model_name='author',
            name='publications',
            field=models.ManyToManyField(to='research.Publication'),
        ),
    ]
