# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20160921_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='pubmed_link',
        ),
        migrations.AddField(
            model_name='author',
            name='google_scholar_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
