# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20160921_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='google_scholar_link',
            new_name='personal_link',
        ),
    ]
