# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20160921_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='publications',
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
